apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-support-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: it-support
  template:
    metadata:
      labels:
        app: it-support
    spec:
      containers:
      - name: app
        # El workflow reemplazará este tag automáticamente
        image: acrcarlos69lm.azurecr.io/app-pro:tmp
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        
        # Sondas de salud optimizadas para Azure SQL
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30 # Damos más tiempo para que Node inicie
          periodSeconds: 20
        
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 20 # Esperamos a que la conexión DB se estabilice
          periodSeconds: 10

        env:
        - name: DB_SERVER
          value: "sql-server-lab21-carlos.database.windows.net"
        - name: DB_NAME
          value: "ticketsdb"
        - name: DB_USER
          value: "sqladmin"
        - name: DB_PASSWORD
          value: "Password1234!"
        - name: PORT
          value: "3000"