apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-support-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: it-support
  template:
    metadata:
      labels:
        app: it-support
    spec:
      containers:
      - name: app
        # Nota: El tag ':tmp' será reemplazado por el ${{ github.run_id }} en el Workflow
        image: acrcarlos69lm.azurecr.io/app-pro:tmp
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        
        # --- Configuración de Salud (Probes) ---
        # Verifica si el contenedor sigue vivo
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        
        # Verifica si el contenedor está listo para recibir tráfico (DB conectada)
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10

        # --- Variables de Entorno para la Conexión a SQL ---
        env:
        - name: DB_SERVER
          value: "sql-server-lab21-carlos.database.windows.net"
        - name: DB_NAME
          value: "ticketsdb"
        - name: DB_USER
          value: "sqladmin"
        - name: DB_PASSWORD
          value: "Password1234!"
        - name: PORT
          value: "3000"