apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-support-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-support
  template:
    metadata:
      labels:
        app: it-support
    spec:
      containers:
      - name: app
        image: acrcarlos69lm.azurecr.io/app-pro:v1
        ports:
        - containerPort: 3000