apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-support-ingress
  annotations:
    # Si usas el addon nativo de Azure:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: it-support-service # Apunta al service privado
            port:
              number: 80